import React, { useState, useCallback } from "react";
import { View } from "react-native";
import { Picker } from "@react-native-picker/picker";
import { styles } from "./InfoForm.styles";

export function RegyCom({ formik, ErrorMessage }) {
  //estado para guardar la region y comunas seleccionadas
  const [selectedRegion, setSelectedRegion] = useState("");
  const [comunas, setComunas] = useState([]);

  //Funcino para cambiar la region y cargar las comunas correspondientes
  const handleRegionChange = useCallback(
    (region) => {
      setSelectedRegion(region);
      const comunasRegion = regionesYComunas[region] || [];
      setComunas(comunasRegion);
      formik.setFieldValue("region", region);
      formik.setFieldValue("city", comunasRegion[0] || "");
    },
    [formik]
  );

  const regionesYComunas = {
    Arica_Parinacota: ["Arica", "Camarones", "Putre", "General Lagos"],
    Tarapacá: [
      "Iquique",
      "Alto Hospicio",
      "Pozo Almonte",
      "Huara",
      "Camiña",
      "Colchane",
      "Pica",
    ],
    Antofagasta: [
      "Antofagasta",
      "Mejillones",
      "Taltal",
      "Sierra Gorda",
      "Calama",
      "Ollagüe",
      "San Pedro de Atacama",
      "Tocopilla",
      "María Elena",
    ],
    Atacama: [
      "Copiapó",
      "Tierra Amarilla",
      "Caldera",
      "Chañaral",
      "Diego de Almagro",
      "Vallenar",
      "Huasco",
      "Freirina",
      "Alto del Carmen",
    ],
    Coquimbo: [
      "La Serena",
      "Coquimbo",
      "La Higuera",
      "Paihuano",
      "Vicuña",
      "Ovalle",
      "Monte Patria",
      "Río Hurtado",
      "Punitaqui",
      "Combarbalá",
      "Illapel",
      "Los Vilos",
      "Salamanca",
      "Canela",
    ],
    Valparaíso: [
      "Valparaíso",
      "Viña del Mar",
      "Concón",
      "Quintero",
      "Puchuncaví",
      "Quilpué",
      "Villa Alemana",
      "Limache",
      "Olmué",
      "Quillota",
      "La Calera",
      "Hijuelas",
      "Nogales",
      "La Ligua",
      "Cabildo",
      "Petorca",
      "Zapallar",
      "Papudo",
      "San Antonio",
      "Cartagena",
      "El Tabo",
      "El Quisco",
      "Algarrobo",
      "Santo Domingo",
      "San Felipe",
      "Catemu",
      "Llaillay",
      "Panquehue",
      "Putaendo",
      "Santa María",
      "Los Andes",
      "San Esteban",
      "Calle Larga",
      "Rinconada",
      "Isla de Pascua",
      "Juan Fernández",
    ],
    Metropolitana: [
      "Santiago",
      "Providencia",
      "Ñuñoa",
      "Las Condes",
      "Vitacura",
      "Lo Barnechea",
      "La Reina",
      "Peñalolén",
      "Macul",
      "La Florida",
      "Puente Alto",
      "Pirque",
      "San José de Maipo",
      "La Granja",
      "San Ramón",
      "La Pintana",
      "El Bosque",
      "San Bernardo",
      "Buin",
      "Paine",
      "Calera de Tango",
      "Cerrillos",
      "Maipú",
      "Estación Central",
      "Pedro Aguirre Cerda",
      "Lo Espejo",
      "Lo Prado",
      "Pudahuel",
      "Cerro Navia",
      "Quinta Normal",
      "Recoleta",
      "Independencia",
      "Renca",
      "Conchalí",
      "Huechuraba",
      "Quilicura",
      "Colina",
      "Lampa",
      "Tiltil",
      "San Miguel",
    ],
    OHiggins: [
      "Rancagua",
      "Machalí",
      "Graneros",
      "Mostazal",
      "Codegua",
      "Coinco",
      "Coltauco",
      "Doñihue",
      "Olivar",
      "Requínoa",
      "Rengo",
      "Malloa",
      "Quinta de Tilcoco",
      "San Vicente",
      "San Fernando",
      "Chimbarongo",
      "Placilla",
      "Nancagua",
      "Santa Cruz",
      "Lolol",
      "Pumanque",
      "Chépica",
      "Palmilla",
      "Peralillo",
      "Pichilemu",
      "Marchigüe",
      "La Estrella",
      "Litueche",
      "Navidad",
    ],
    Maule: [
      "Talca",
      "San Clemente",
      "Pelarco",
      "Pencahue",
      "Maule",
      "Río Claro",
      "Curepto",
      "Constitución",
      "Empedrado",
      "Linares",
      "Yerbas Buenas",
      "Colbún",
      "Longaví",
      "Parral",
      "Retiro",
      "San Javier",
      "Villa Alegre",
      "Cauquenes",
      "Chanco",
      "Pelluhue",
      "Curicó",
      "Romeral",
      "Teno",
      "Hualañé",
      "Licantén",
      "Vichuquén",
      "Molina",
      "Sagrada Familia",
      "Rauco",
    ],
    Ñuble: [
      "Chillán",
      "Chillán Viejo",
      "El Carmen",
      "Pemuco",
      "Pinto",
      "Coihueco",
      "San Ignacio",
      "Yungay",
      "Quirihue",
      "Cobquecura",
      "Ninhue",
      "Ránquil",
      "Trehuaco",
      "San Carlos",
      "Ñiquén",
      "San Fabián",
      "San Nicolás",
      "Bulnes",
      "Quillón",
    ],
    Biobío: [
      "Concepción",
      "Talcahuano",
      "Hualpén",
      "Penco",
      "Tomé",
      "Chiguayante",
      "San Pedro de la Paz",
      "Coronel",
      "Lota",
      "Santa Juana",
      "Hualqui",
      "Florida",
      "Los Ángeles",
      "Nacimiento",
      "Laja",
      "San Rosendo",
      "Santa Bárbara",
      "Quilaco",
      "Mulchén",
      "Negrete",
      "Quilleco",
      "Antuco",
      "Cabrero",
      "Yumbel",
      "Tucapel",
      "Alto Biobío",
      "Arauco",
      "Curanilahue",
      "Lebu",
      "Los Álamos",
      "Cañete",
      "Contulmo",
      "Tirúa",
    ],
    Araucanía: [
      "Temuco",
      "Padre Las Casas",
      "Carahue",
      "Nueva Imperial",
      "Saavedra",
      "Cholchol",
      "Cunco",
      "Freire",
      "Pitrufquén",
      "Teodoro Schmidt",
      "Toltén",
      "Loncoche",
      "Villarrica",
      "Pucón",
      "Curarrehue",
      "Lautaro",
      "Perquenco",
      "Vilcún",
      "Melipeuco",
      "Galvarino",
      "Traiguén",
      "Victoria",
      "Curacautín",
      "Lonquimay",
      "Collipulli",
      "Angol",
      "Ercilla",
      "Renaico",
      "Purén",
      "Los Sauces",
      "Lumaco",
    ],
    LosRíos: [
      "Valdivia",
      "Corral",
      "Lanco",
      "Máfil",
      "Mariquina",
      "Paillaco",
      "Panguipulli",
      "Los Lagos",
      "Futrono",
      "La Unión",
      "Río Bueno",
      "Lago Ranco",
    ],
    LosLagos: [
      "Puerto Montt",
      "Puerto Varas",
      "Cochamó",
      "Maullín",
      "Calbuco",
      "Llanquihue",
      "Frutillar",
      "Fresia",
      "Los Muermos",
      "Ancud",
      "Castro",
      "Chonchi",
      "Curaco de Vélez",
      "Dalcahue",
      "Puqueldón",
      "Queilén",
      "Quellón",
      "Quemchi",
      "Quinchao",
      "Osorno",
      "Puerto Octay",
      "Purranque",
      "Puyehue",
      "Río Negro",
      "San Juan de la Costa",
      "San Pablo",
      "Chaitén",
      "Futaleufú",
      "Hualaihué",
      "Palena",
    ],
    Aysén: [
      "Coyhaique",
      "Lago Verde",
      "Aysén",
      "Cisnes",
      "Guaitecas",
      "Chile Chico",
      "Río Ibáñez",
      "Cochrane",
      "O'Higgins",
      "Tortel",
    ],
    Magallanes: [
      "Punta Arenas",
      "Laguna Blanca",
      "Río Verde",
      "San Gregorio",
      "Puerto Natales",
      "Torres del Paine",
      "Cabo de Hornos",
      "Antártica",
    ],
  };
  return (
    <View style={styles.row}>
      <View style={styles.pickerContainer}>
        <Picker
          selectedValue={selectedRegion}
          onValueChange={handleRegionChange}
          style={styles.picker}
        >
          <Picker.Item label="Región" value="" />
          {Object.keys(regionesYComunas).map((region) => (
            <Picker.Item key={region} label={region} value={region} />
          ))}
        </Picker>
        <ErrorMessage error={formik.errors.region} />
      </View>

      <View style={styles.pickerContainer}>
        <Picker
          selectedValue={formik.values.city}
          onValueChange={(value) => formik.setFieldValue("city", value)}
          style={styles.picker}
        >
          <Picker.Item label="Comuna" value="" />
          {comunas.map((comuna) => (
            <Picker.Item key={comuna} label={comuna} value={comuna} />
          ))}
        </Picker>
        <ErrorMessage error={formik.errors.city} />
      </View>
    </View>
  );
}
