// regionsWithCommunes.js

const regionesYComunas = [
  {
    region: "Región de Arica y Parinacota",
    comunas: ["Arica", "Camarones", "Putre", "General Lagos"],
  },
  {
    region: "Región de Tarapacá",
    comunas: [
      "Iquique",
      "Alto Hospicio",
      "Pozo Almonte",
      "Huara",
      "Camiña",
      "Colchane",
      "Pica",
    ],
  },
  {
    region: "Región de Antofagasta",
    comunas: [
      "Antofagasta",
      "Mejillones",
      "Taltal",
      "Sierra Gorda",
      "Calama",
      "Ollagüe",
      "San Pedro de Atacama",
      "Tocopilla",
      "María Elena",
    ],
  },
  {
    region: "Región de Atacama",
    comunas: [
      "Copiapó",
      "Tierra Amarilla",
      "Caldera",
      "Chañaral",
      "Diego de Almagro",
      "Vallenar",
      "Huasco",
      "Freirina",
      "Alto del Carmen",
    ],
  },
  {
    region: "Región de Coquimbo",
    comunas: [
      "La Serena",
      "Coquimbo",
      "La Higuera",
      "Paihuano",
      "Vicuña",
      "Ovalle",
      "Monte Patria",
      "Río Hurtado",
      "Punitaqui",
      "Combarbalá",
      "Illapel",
      "Los Vilos",
      "Salamanca",
      "Canela",
    ],
  },
  {
    region: "Región de Valparaíso",
    comunas: [
      "Valparaíso",
      "Viña del Mar",
      "Concón",
      "Quintero",
      "Puchuncaví",
      "Quilpué",
      "Villa Alemana",
      "Limache",
      "Olmué",
      "Quillota",
      "La Calera",
      "Hijuelas",
      "Nogales",
      "La Ligua",
      "Cabildo",
      "Petorca",
      "Zapallar",
      "Papudo",
      "San Antonio",
      "Cartagena",
      "El Tabo",
      "El Quisco",
      "Algarrobo",
      "Santo Domingo",
      "San Felipe",
      "Catemu",
      "Llaillay",
      "Panquehue",
      "Putaendo",
      "Santa María",
      "Los Andes",
      "San Esteban",
      "Calle Larga",
      "Rinconada",
      "Isla de Pascua",
      "Juan Fernández",
    ],
  },
  {
    region: "Región Metropolitana de Santiago",
    comunas: [
      "Santiago",
      "Providencia",
      "Ñuñoa",
      "Las Condes",
      "Vitacura",
      "Lo Barnechea",
      "La Reina",
      "Peñalolén",
      "Macul",
      "La Florida",
      "Puente Alto",
      "Pirque",
      "San José de Maipo",
      "La Granja",
      "San Ramón",
      "La Pintana",
      "El Bosque",
      "San Bernardo",
      "Buin",
      "Paine",
      "Calera de Tango",
      "Cerrillos",
      "Maipú",
      "Estación Central",
      "Pedro Aguirre Cerda",
      "Lo Espejo",
      "Lo Prado",
      "Pudahuel",
      "Cerro Navia",
      "Quinta Normal",
      "Recoleta",
      "Independencia",
      "Renca",
      "Conchalí",
      "Huechuraba",
      "Quilicura",
      "Colina",
      "Lampa",
      "Tiltil",
      "San Miguel",
    ],
  },
  {
    region: "Región del Libertador General Bernardo O'Higgins",
    comunas: [
      "Rancagua",
      "Machalí",
      "Graneros",
      "Mostazal",
      "Codegua",
      "Coinco",
      "Coltauco",
      "Doñihue",
      "Olivar",
      "Requínoa",
      "Rengo",
      "Malloa",
      "Quinta de Tilcoco",
      "San Vicente",
      "San Fernando",
      "Chimbarongo",
      "Placilla",
      "Nancagua",
      "Santa Cruz",
      "Lolol",
      "Pumanque",
      "Chépica",
      "Palmilla",
      "Peralillo",
      "Pichilemu",
      "Marchigüe",
      "La Estrella",
      "Litueche",
      "Navidad",
    ],
  },
  {
    region: "Región del Maule",
    comunas: [
      "Talca",
      "San Clemente",
      "Pelarco",
      "Pencahue",
      "Maule",
      "Río Claro",
      "Curepto",
      "Constitución",
      "Empedrado",
      "Linares",
      "Yerbas Buenas",
      "Colbún",
      "Longaví",
      "Parral",
      "Retiro",
      "San Javier",
      "Villa Alegre",
      "Cauquenes",
      "Chanco",
      "Pelluhue",
      "Curicó",
      "Romeral",
      "Teno",
      "Hualañé",
      "Licantén",
      "Vichuquén",
      "Molina",
      "Sagrada Familia",
      "Rauco",
    ],
  },
  {
    region: "Región de Ñuble",
    comunas: [
      "Chillán",
      "Chillán Viejo",
      "El Carmen",
      "Pemuco",
      "Pinto",
      "Coihueco",
      "San Ignacio",
      "Yungay",
      "Quirihue",
      "Cobquecura",
      "Ninhue",
      "Ránquil",
      "Trehuaco",
      "San Carlos",
      "Ñiquén",
      "San Fabián",
      "San Nicolás",
      "Bulnes",
      "Quillón",
    ],
  },
  {
    region: "Región del Biobío",
    comunas: [
      "Concepción",
      "Talcahuano",
      "Hualpén",
      "Penco",
      "Tomé",
      "Chiguayante",
      "San Pedro de la Paz",
      "Coronel",
      "Lota",
      "Santa Juana",
      "Hualqui",
      "Florida",
      "Los Ángeles",
      "Nacimiento",
      "Laja",
      "San Rosendo",
      "Santa Bárbara",
      "Quilaco",
      "Mulchén",
      "Negrete",
      "Quilleco",
      "Antuco",
      "Cabrero",
      "Yumbel",
      "Tucapel",
      "Alto Biobío",
      "Arauco",
      "Curanilahue",
      "Lebu",
      "Los Álamos",
      "Cañete",
      "Contulmo",
      "Tirúa",
    ],
  },
  {
    region: "Región de La Araucanía",
    comunas: [
      "Temuco",
      "Padre Las Casas",
      "Carahue",
      "Nueva Imperial",
      "Saavedra",
      "Cholchol",
      "Cunco",
      "Freire",
      "Pitrufquén",
      "Teodoro Schmidt",
      "Toltén",
      "Loncoche",
      "Villarrica",
      "Pucón",
      "Curarrehue",
      "Lautaro",
      "Perquenco",
      "Vilcún",
      "Melipeuco",
      "Galvarino",
      "Traiguén",
      "Victoria",
      "Curacautín",
      "Lonquimay",
      "Collipulli",
      "Angol",
      "Ercilla",
      "Renaico",
      "Purén",
      "Los Sauces",
      "Lumaco",
    ],
  },
  {
    region: "Región de Los Ríos",
    comunas: [
      "Valdivia",
      "Corral",
      "Lanco",
      "Máfil",
      "Mariquina",
      "Paillaco",
      "Panguipulli",
      "Los Lagos",
      "Futrono",
      "La Unión",
      "Río Bueno",
      "Lago Ranco",
    ],
  },
  {
    region: "Región de Los Lagos",
    comunas: [
      "Puerto Montt",
      "Puerto Varas",
      "Cochamó",
      "Maullín",
      "Calbuco",
      "Llanquihue",
      "Frutillar",
      "Fresia",
      "Los Muermos",
      "Ancud",
      "Castro",
      "Chonchi",
      "Curaco de Vélez",
      "Dalcahue",
      "Puqueldón",
      "Queilén",
      "Quellón",
      "Quemchi",
      "Quinchao",
      "Osorno",
      "Puerto Octay",
      "Purranque",
      "Puyehue",
      "Río Negro",
      "San Juan de la Costa",
      "San Pablo",
      "Chaitén",
      "Futaleufú",
      "Hualaihué",
      "Palena",
    ],
  },
  {
    region: "Región de Aysén del General Carlos Ibáñez del Campo",
    comunas: [
      "Coyhaique",
      "Lago Verde",
      "Aysén",
      "Cisnes",
      "Guaitecas",
      "Chile Chico",
      "Río Ibáñez",
      "Cochrane",
      "O'Higgins",
      "Tortel",
    ],
  },
  {
    region: "Región de Magallanes y de la Antártica Chilena",
    comunas: [
      "Punta Arenas",
      "Laguna Blanca",
      "Río Verde",
      "San Gregorio",
      "Puerto Natales",
      "Torres del Paine",
      "Cabo de Hornos",
      "Antártica",
    ],
  },
];

export default regionesYComunas;
